### ISSUE TITLE
Save Previously Connected Devices

### ISSUE THREAD

**Issue by Khantahr** [y-polek/ADB-Wi-Fi#1]
Please add a feature to save devices so I don't have to plug in a USB cable to connect a device that I have connected to previously.

**Comment by y-polek** [comment]
"Previously connected devices" list is implemented in [1.1.0](https://github.com/y-polek/ADB-Wi-Fi/releases/tag/v1.1.0)
Devices are automatically added to the list after the first successful adb-over-wifi connection.

Please note that the connection attempt from the "previously connected" list won't always succeed.
Particularly it won't work after the device's reboot. In this case, you have to connect your device with a USB cable and perform a connection manually.

Also, a connection might fail if the device is asleep. In this case screen wakeup usually helps.
