### ISSUE TITLE
Incompatible IntelliJ 2021.2

### ISSUE THREAD

**Issue by luiscarielo83** [y-polek/ADB-Wi-Fi#12]
Incompatible with the new version of IntelliJ IDEA (Incompatible: requires IDE build 211.* or older)

IntelliJ IDEA 2021.2 (Community Edition)
Build #IC-212.4746.92, built on July 27, 2021
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4

**Comment by y-polek** [comment]
Thanks!
Fixed in [v1.2.3](https://github.com/y-polek/ADB-Wi-Fi/releases/tag/v1.2.3).
It should be available through Marketplace in up to two days.

**Comment by luiscarielo83** [comment]
Thnaks you @y-polek
