### ISSUE TITLE
This Plugin is't compatible with scrcpy 1.21

### ISSUE THREAD

**Issue by Vixb1122** [y-polek/ADB-Wi-Fi#16]
![image](https://user-images.githubusercontent.com/17810492/145144744-aebe3bb1-2180-4d73-95f4-7658daf8f3a3.png)

**Comment by y-polek** [comment]
This issue is caused by this scrcpy issue: Genymobile/scrcpy#2838
The fix will be available in the next scrcpy version.
Until then as a workaround, you can replace `scrcpy.exe` file in your scrcpy-1.21 release folder with one from this PR: Genymobile/scrcpy#2840
