### ISSUE TITLE
The plugin gets the wrong IP address

### ISSUE THREAD

**Issue by zeemanz** [y-polek/ADB-Wi-Fi#2]
When my phone turn on the mobile network and Wi-Fi at the same time, this plugin will get the IP address of the mobile network instead of Wi-Fi(Local Area Network). So it will not be able to connect to my phone.
After I read the code, I guess the cause of this problem comes from this method at
```
// ADB-Wi-Fi/src/main/kotlin/dev/polek/adbwifi/adb/Adb.kt    Line 105-108
private fun address(deviceId: String): String? {
    val firstLine = "-s $deviceId shell ip route".exec().firstLine()
    return DEVICE_ADDRESS_REGEX.matchEntire(firstLine)?.groupValues?.get(1)
}
```
When I turn on the mobile network and Wi-Fi together, the return result of command `adb shell ip route` is as follows
![image](https://user-images.githubusercontent.com/57309261/94859499-360e9500-0467-11eb-85e4-7f31d9243ca8.png)
As you can see, the first line of the result is not the IP address of Wi-Fi.

**Comment by y-polek** [comment]
@zzimo9865 Thank you for the bug report!

Just submitted [1.1.1](https://github.com/y-polek/ADB-Wi-Fi/releases/tag/v1.1.1) with the fix for moderation.
It should be available in the Marketplace within two business days.
