### ISSUE TITLE
Mobile Hotspot IP

### ISSUE THREAD

**Issue by leosilberg** [y-polek/ADB-Wi-Fi#4]
Hi 

When I'm connected to my mobile hotspot and the internet it's not possible to connect to the hotspots IP 

`adb shell ip route` gives me this output

192.168.43.0/24 dev swlan0 proto kernel scope link src 192.168.43.1

Please add an option to connect to this IP 
Thanks by the way for this awesome plugin, really helpful

**Comment by y-polek** [comment]
In [1.2.1](https://github.com/y-polek/ADB-Wi-Fi/releases/tag/v1.2.1) device list shows one entry for each IP address.
It allows users to choose which IP should be used for a connection.

Icon of network type is shown next to the IP address to help distinguish different IP addresses:
![wifiNetwork](https://user-images.githubusercontent.com/6666447/102833007-983cbd80-43f8-11eb-80e6-2d46a4c55702.png) - regular Wi-Fi network (`wlan*` interface)
![hotspotNetwork](https://user-images.githubusercontent.com/6666447/102832972-7e9b7600-43f8-11eb-98a4-dade5ab2d97f.png) - tethering network (`swlan*`, `ap*` interfaces)
![mobileNetwork](https://user-images.githubusercontent.com/6666447/102833028-a5f24300-43f8-11eb-9ef6-c7e3300ad717.png) - mobile network (`rmnet*`, `ccmni*` interfaces)
