### ISSUE TITLE
How to use with scrcpy?

### ISSUE THREAD

**Issue by Vixb1122** [y-polek/ADB-Wi-Fi#6]
Can't find the button to start scrcpy
![image](https://user-images.githubusercontent.com/17810492/101120186-f2cbd080-3627-11eb-8b48-fa2c775b623a.png)
![image](https://user-images.githubusercontent.com/17810492/101120212-fe1efc00-3627-11eb-8081-f22154fc6da1.png)

**Comment by y-polek** [comment]
It is a button in the right-bottom corner, to the left of the menu button.

<img width="386" alt="adb-wi-fi-scrcpy" src="https://user-images.githubusercontent.com/6666447/101157990-adad9b80-3633-11eb-8b90-45ab0f13f8db.png">
