### ISSUE TITLE
Feature Request: input ip and port to connect device

### ISSUE THREAD

**Issue by Vixb1122** [y-polek/ADB-Wi-Fi#7]
![image](https://user-images.githubusercontent.com/17810492/101120392-7ab1da80-3628-11eb-9097-13d1b2a8bcf7.png)

**Comment by y-polek** [comment]
In [1.2.1](https://github.com/y-polek/ADB-Wi-Fi/releases/tag/v1.2.1) "Connect Device" action is added to plugin window toolbar:

<img width="489" alt="connect_device1" src="https://user-images.githubusercontent.com/6666447/102833542-0cc42c00-43fa-11eb-8b31-f3b50436871e.png">
<img width="391" alt="Screenshot 2020-12-22 at 02 05 16" src="https://user-images.githubusercontent.com/6666447/102833581-2bc2be00-43fa-11eb-9347-f9858163f205.png">

For now, it doesn't support port number (it always uses default port 5555).
Non-default port numbers support will be tracked in #8
